### ISSUE TITLE
add more typedefs

### ISSUE THREAD

**Issue by sritchie** [unconed/mathbox#16]
#25 Introduced infrastructure for typings. Remaining TODOs:

### To-do:
- [x] add typings for `mathBox` options
- [ ] finish manual typings for `types.js`
- [x] add more tests to `types.spec.ts`. Since that test file is written in typescript, if its tests pass, we can be confident in my manual typings.

**Comment by ChristopherChudzicki** [comment]
The types for `types.js` are not really done. A bunch are still `any`: https://github.com/unconed/mathbox/blob/master/src/primitives/types/types_typed.ts#L207-L222

I think this will be "done" when those are all finished. I'm pretty sure I'll add `scale` soon, and will look more closely at the others when I do that.
